repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run pytest
        entry: pytest  # This will run pytest on the entire repo
        language: system
        types: [python]